application:
  name: SpringCodeGenKt

db:
  url: jdbc:mysql://127.0.0.1:3306/codegen?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
  username: root
  password: emmmm000
  driver-class-name: com.mysql.cj.jdbc.Driver

ignore:
  # 忽略表前缀
  table-prefix: true

# 生成 bean查询参数文件 的后缀
suffix-bean-param: Query
# 模糊查询字符串 的后缀
suffix-bean-param-fuzzy: Fuzzy
# 模糊查询时间 开始 的后缀
suffix-bean-param-time-start: Start
# 模糊查询时间 结束 的后缀
suffix-bean-param-time-end: End
# controller 的后缀
suffix-controller: Controller
# service 的后缀
suffix-service: Service
# service impl 的后缀
suffix-service-impl: ServiceImpl
# mapper 的后缀
suffix-mapper: Mapper
# 日期相关
date-format:
  expression: "DateTimeFormat"
  import-class: "org.springframework.format.annotation.DateTimeFormat"

path:
  output-dir: D:/code/kotlin/CodeGen/TestCodeGen/src/main
package-config:
  base: io.github.hcisme.testcodegen
  pojo: entity.pojo
  query: entity.query
  enums: entity.enums
  vo: entity.vo
  controller: controller
  service: service
  service-impl: impl
  mappers: mappers
  utils: utils