application:
  name: SpringCodeGenKt

db:
  url: jdbc:mysql://127.0.0.1:3306/codegen?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
  username: root
  password: emmmm000
  driver-class-name: com.mysql.cj.jdbc.Driver

ignore:
  # 忽略表前缀
  table-prefix: true

# 生成 bean查询参数 的前缀
suffix-bean-param: Param
# 日期相关
date-format:
  expression: "@DateTimeFormat"
  import-class: "org.springframework.format.annotation.DateTimeFormat"

path:
  output-dir: D:/code/kotlin/CodeGen/TestCodeGen/src/main
package-config:
  base: io.github.hcisme.testcodegen
  pojo: entity.pojo
  param: entity.param